### PR TITLE
Update to python3 for nemo-extensions>=3.9.0

### PR DESCRIPTION
**Pull request by twa022**
nemo-python 3.9.0 is ported to python3

### CODE REVIEW

**Comment by linux-man** [comment]
Since I don't know who to change a request branch, I created python3 and added the modifications you proposed. As urllib loading was managed differently on caja and nautilus mediainfo-tab I took the chance to normalize all.
I can't test the code (don't have python-nemo 3.9.0), so I hope it's all OK.

**Comment by linux-man** [comment]
As far as I know, Arch is the only distro with nemo and nautilus python3 bindings, so this may interest to @yochananmarqos. I created a new release.

**Comment by yochananmarqos** [comment]
@linux-man Once `nemo-python` 3.9.0 hits Manjaro Stable, I'll test it.

**Comment by linux-man** [comment]
Closing with thanks to @twa022 for the opportunity to make mediainfo-tab better.

**Pull request closed without merging**
